spring:
  application:
    name: fcjs-api-server
  profiles:
    active: dev

server:
  tomcat:
    basedir: /data/server/log
    accesslog:
      directory: logs
      enabled: true
      pattern: common
